### ISSUE TITLE
Editable header

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#256]
Making the header and footer editable by content designers has been discussed previously. 

We need to confirm whether any work was done or not.

If not, we need to decide on a MVP to deliver in a future sprint.

## User story 

As a content designer
I want to be able to edit the logo and links in the header.
So that I can brand this with my council's logo and set some top level menu items

## Tasks

- [x] Talk to @andybroomfield and find out what work has been done to date
- [x] Test the permissions as a content designer / content editor
- [ ] Line up dev tasks if needed
- [x] Add search form to header

Acceptance tests: 
 t.b.c.

**Comment by stephen-cox** [comment]
@andybroomfield I'm looking at adding an editable header menu that is installed by default along with some footer blocks. Are you aware of any work that has been done on this sort of thing already?

**Comment by stephen-cox** [comment]
@willguv The header already include a logo and the main navigation menu, so the bulk of this is ensuring content designers have the correct permissions.

For the menu, Drupal comes with an 'Administer menus' permission this allows access to create and edit any menu on the site. Is this too lax? If so I'll look at solutions to restrict which menus a content designer can edit.

For the logo, Drupal comes with an 'Administer themes' permission which gives access to switch the theme in use as well as changing the logo and favicon. This sounds too lax to me so I'll look at options to restrict this to the current enabled theme, but let me know if you think having access to all themes is okay.

**Comment by willguv** [comment]
Hi @stephen-cox this feeds into the content lifecycle working group conversation we've been having. 

I think these permissions are OK to grant, providing they're assigned to an appropriate role

See @finnlewis' user stories which sets out proposed new roles

https://localgovdrupal.slack.com/archives/C01TS349XCY/p1623772892001100

Feels like this is suitable for a "content administrator" and I can raise it tomorrow

**Comment by andybroomfield** [comment]
So as a rule at BHCC we don't allow the header and footer to be editable by content design team, as that's a more formal change that needs to be signed off.

Also I think a lot of it is hard coded, but the direction of travel is to make it the Drupal way. However some things are config and shouldn't generally be changed unless a dev request.

That said, changing a logo is under appearance if the right permissions are assigned, as is site name and settings (careful with permissions on this, this can change more than you bargain for)

Menus generally are considered content and are editable. Blocks are a mix of config and content so if your going to make these editable you'll need to add something to config ignore / config split.

I have been thinking it would be worth while having a 'My Council' settings page for logo, council name, social media links, main contact address. Then use the contents of those for blocks. That might be safer as it's something that can either be defined as content or a config that can easily be ignored for version control if required.

**Comment by andybroomfield** [comment]
@stephen-cox As the user story is only edit logo and menu, I think there is a module to grant limited permissions over certain menus

**Comment by willguv** [comment]
@andybroomfield this is useful - thanks. I can add it to the discussion tomorrow
