### ISSUE TITLE
Site-wide search - default implementation  out of the box

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#259]
## User story

As a content designer
I want: site wide search out of the box
So that: I can have basic search 

## Assumptions: 

 - basic first pass
 - all content types to be indexed
 - fields to be indexed: rendered page or a specific view mode
 - search result view mode (check with @markconroy )
 - no filters (for now)
 - minimal theme work for now, but test in current localgov_theme theme

## Acceptance tests

 - from a default install:
 - go to /search 
 - see search box
 - search for a thing
 - see a list of relevant things

## Tasks:

- [x] whip up a wireframe 
- [x] set up new module with search api dependency etc. 
- [x] search view config for /search
- [x] search index view mode on all content types
- [x] search result view mode on all content types
- [x] Implement wireframe
- [x] Tests

**Comment by msayoung** [comment]
@stephen-cox there's a wireframe here: https://design.penpot.app/#/view/f220dcf0-c3e1-11eb-8557-f55ab9adbb41/f220dcf1-c3e1-11eb-8557-f55ab9adbb41?index=0

**Comment by danchamp** [comment]
@msayoung A little accessibility feedback on the wireframe:

- An explicit `<label>` for search field would preferred - the button is liable to be styled with just an icon or some other markup that may not translate sensibly to an accessible name.
- The label can be hidden using an accessible method (I'm assuming @markconroy will have a utility class for accessible hiding in localgov_base).
- If we're not using a label, an explicit `aria-label` value of 'Search' or similar would be better than `aria-labelledby`.
- The `<form>` element (or its parent or a child container) should have the attribute `role="search"` and the form should have a unique id to support multiple search forms on the page, for instance when in directories.
- It's good practice to keep the search term value after submission, to prevent user having to re-type the whole term is refining it - we could show this on the results wireframe.
- Reset link - what does it do? Without any filtering, sorting or other options it seems redundant? The user can just search for something else.
- I think the default Drupal search uses an ordered list for results, which is fine.

**Comment by msayoung** [comment]
Thanks @danchamp 
> * An explicit `<label>` for search field would preferred - the button is liable to be styled with just an icon or some other markup that may not translate sensibly to an accessible name.

Sure, I have put an explicit label in, and renamed the button to "Apply" to a) avoid repetition, and b) follow what we have on other lists of things. eg /events 

I've incorporated your other comments directly into the wireframe.

**Comment by markconroy** [comment]
In terms of an accessible utility class to hide the label, Drupal has a built in `.visually-hidden` class that can be used.

However, if we use that in the template we are saying that _every_ website using this wants to have the label hidden by default. This is fine if that's our decision, just want to raise it here. The opposite is the same, saying _every_ website using this wants the form visible.

**Comment by markconroy** [comment]
@msayoung can I have access to that wireframe please? mark@annertech.com. thanks.

**Comment by stephen-cox** [comment]
@willguv and anyone else who maybe interested, the work on implementing the sitewide search is ready to be tested here: https://test.localgovdrupal.org/search

I will put together all the PRs associated with this tomorrow, but please let me know if you have any feedback on the implementation so far.

**Comment by markconroy** [comment]
Hi @stephen-cox 

This is looking really nice, thanks.

I don't think we should have `role="alert"` on every search result, and think it would be better to use `article` for the container element instead of `div`. Is what is currently there just default out of the box stuff from Drupal? If so, then maybe it's right to use it.

**Comment by stephen-cox** [comment]
@markconroy Thanks. Good catch on the search result HTML. There is some basic theming for the sitewide search in locagov_theme and have updated the templates. There's a PR for the theming changes here: https://github.com/localgovdrupal/localgov_theme/pull/195

**Comment by markconroy** [comment]
Thanks @stephen-cox 
I've left a review of that PR.

**Comment by willguv** [comment]
@stephen-cox looks great. My only questions are:

- what's the h1 wording?
- what's the button label? Haven't seen "Apply" used anywhere, and GOV.UK seems to use an icon these days https://www.gov.uk/search

**Comment by msayoung** [comment]
Apply" is what we have on the search on events listings etc : https://localgovdrupal.agile.coop/events  and directories https://localgovdrupal.agile.coop/localgov-drupal-collaborators

**Comment by danchamp** [comment]
It's the Drupal default, isn't it? On news it was changed to 'Search'.

One of 'Submit', 'Search', or a bare icon with an appropriate text alternative would be my preference.

**Comment by willguv** [comment]
@msayoung that will teach me to pay attention :)

**Comment by msayoung** [comment]
I don't mind what we use, but we should be consistent. 

If the input label is Search, then the button label could be Submit / Apply or just the icon (with an accessible label) . 
Who's going to make this decision?

**Comment by danchamp** [comment]
I think this provides persuasive evidence for a bare icon:

https://github.com/alphagov/govuk-design-system-backlog/issues/132#issuecomment-378536462

(Without the placeholder text.)

**Comment by willguv** [comment]
I think follow Gov.uk on this occasion

**Comment by msayoung** [comment]
@stephen-cox
If I've interpreted @danchamp correctly, I think we just need to add a `.visually-hidden` class to the <span> surrounding the button text. 
(I'm suggesting that over alt text as the icon is currently loaded via a css background image)

**Comment by danchamp** [comment]
@msayoung @stephen-cox 

> If I've interpreted @danchamp correctly, I think we just need to add a `.visually-hidden` class to the surrounding the button text.

That will work, preserving the hidden element as the accessible name.

> (I'm suggesting that over alt text as the icon is currently loaded via a css background image)

Do you mean currently in LGD? localgov_theme uses Font Awesome as button::after (from the _directories.scss partial, oddly: https://github.com/localgovdrupal/localgov_theme/blob/9aca9ab6a60738dfa6b549fb6741638f406da7fc/assets/scss/lib/partials/_directories.scss#L145-L177)

I don't think there's a button with an icon yet in localgov_base, for button-styled links @markconroy has used inline SVGs for icons contained in a div with an `aria-hidden` attribute.

Gov UK uses a positioned background image (a sprite with 2 icon sizes in the same image).

> I don't mind what we use, but we should be consistent.

Agreed!

**Comment by markconroy** [comment]
I want to get theming done on this asap, but can't really without it being part of the profile since it's so many PRs in different repos.

It looks to me like we are all in agreement with most of what is currently done and the only thing we need to finalise is an approach to the submit button - icon vs text vs inline svg vs background image.

If that's the case, let's get this merged to the profile so we can start working on it and we can figure out the submit button in a separate issue.

**Comment by stephen-cox** [comment]
There's a PR to add the search to the profile here: https://github.com/localgovdrupal/localgov/pull/273. I think the search module needs a code review before including into the profile.

@ekes @Adnan-cds @danchamp @andybroomfield do you have time to look over the [localgov_search](https://github.com/localgovdrupal/localgov_search) module?

There's also a bunch of PRs to add the necessary view modes to all contents types:

- localgovdrupal/localgov_directories#120
- localgovdrupal/localgov_guides#59
- localgovdrupal/localgov_step_by_step#38
- localgovdrupal/localgov_events#35
- localgovdrupal/localgov_services#120

Finally there's some theming in the current theme to make this look okay; localgovdrupal/localgov_theme#195. I think the actual styling of this in the current theme needs reviewing and fixing up.

@markconroy You can pull in all these changes by checking out and installing the `feature/localgov-259-search-2.x` branch on the project.
