### ISSUE TITLE
Directories: Open referral data structure implementation

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#263]

**Comment by ekes** [comment]
So I rolled back on this while doing localgovdrupal/localgov_directories#123 As mentioned https://forum.openreferraluk.org/t/localgov-drupal-implementation/106/2#json-service-4 I think we want to have a chat before jumping one way of the other on the entity type. I was convinced that a custom entity was the way to go; I'm now pretty convinced a node type is the way to go.

**Comment by ekes** [comment]
# Tasks Agreed

- [x] Create node Organisation Directory entry type.
- [x] Create reference field to Organisation that allows directly creating stub Organisation nodes (free tagging style) that are not in a directory.
- [x] Make this field a requirement for a directory being exposed with OR
