### ISSUE TITLE
Add strict type checking

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/localgov#685]
Drupal is moving towards strict type (https://www.drupal.org/project/drupal/issues/3404246, https://www.drupal.org/project/drupal/issues/3295295).

I have started adding improvements to PHPStan checks to run strict type checking, as part of this it includes a new dev package in the project called `phpstan/phpstan-strict-rules`. By default I've disabled most of the rules it provides apart from checking calls are strict.

The checks can be found in this PR https://github.com/localgovdrupal/localgov_project/pull/153 where the previous deprecated check is now a static analysis check to report all modules for deprecations, strict calls and typing.

Overall there are only 129 strict type/call issues which is great as this means minimal work to update.

This ticket would be best used to track updating each module.

- [x] [localgov_alert_banner](https://github.com/localgovdrupal/localgov_alert_banner/issues/313)
- [x] [localgov_core](https://github.com/localgovdrupal/localgov_core/issues/210)
- [x] [localgov_demo](https://github.com/localgovdrupal/localgov_demo/issues/121)
- [ ] [localgov_directories](https://github.com/localgovdrupal/localgov_directories/issues/369)
- [x] [localgov_events](https://github.com/localgovdrupal/localgov_events/issues/142)
- [ ] [localgov_geo](https://github.com/localgovdrupal/localgov_geo/issues/114)
- [x] [localgov_guides](https://github.com/localgovdrupal/localgov_guides/issues/148)
- [ ] [localgov_menu_link_group](https://github.com/localgovdrupal/localgov_menu_link_group/issues/34)
- [x] [localgov_news](https://github.com/localgovdrupal/localgov_news/issues/108)
- [x] [localgov_openreferral](https://github.com/localgovdrupal/localgov_openreferral/issues/52)
- [x] [localgov_page_components](https://github.com/localgovdrupal/localgov_page_components/issues/49)
- [x] [localgov_paragraphs](https://github.com/localgovdrupal/localgov_paragraphs/issues/172)
- [x] [localgov_search](https://github.com/localgovdrupal/localgov_search/issues/71)
- [x] [localgov_search_solr](https://github.com/localgovdrupal/localgov_search_solr/issues/17)
- [ ] [localgov_services](https://github.com/localgovdrupal/localgov_services/issues/253)
- [x] [localgov_step_by_step](https://github.com/localgovdrupal/localgov_step_by_step/issues/97)
- [x] [localgov_subsites](https://github.com/localgovdrupal/localgov_subsites/issues/144)
- [ ] [localgov_workflows](https://github.com/localgovdrupal/localgov_workflows/issues/83)
- [x] [localgov (profile)](https://github.com/localgovdrupal/localgov/issues/690)
